config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :libros
  resources :utentes
  resources :annuncios
  root 'homepage#index'

  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get   'new_annuncio' => 'annuncios#new'

end

app/models/annuncio.rb
class Annuncio < ApplicationRecord
	belongs_to :user, optional: true
	default_scope -> { order(created_at: :desc) }
   	validates :utente_id, presence: true
   	validates :descrizione, presence: true, length: { maximum: 300 }
   	validates :visibilita, numericality: true, inclusion: {in: 0..10 }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/facoltum.rb
class Facoltum < ApplicationRecord
	set_primary_key :nome
end

app/models/libro.rb
class Libro < ApplicationRecord
	self.primary_key= :ISBN
end

app/models/regione.rb
class Regione < ApplicationRecord
	set_primary_key :nome
end

app/models/utente.rb
class Utente < ApplicationRecord
	self.primary_key= :username

	has_many :annuncios, dependent: :destroy

	validates :username, length: { maximum: 10,
    too_long: "%{count} caratteri al massimo" }
    validates_presence_of :username, :nome,:cognome,:email,:password,:password_confirmation, :message => "Campo obbligatorio" 

    validates :password,length: { minimum: 6,
    too_short: "minimo %{count} caratteri" }, confirmation: true


    has_secure_password
end

app/controllers/annuncios_controller.rb
class AnnunciosController < ApplicationController
	before_action :logged_in_user, only: [:create, :destroy]

  def index
    @annuncios = Annuncio.all
  end

	def new 
		@annuncio = Annuncio.new
	end

	def create
    @annuncio = current_utente.annuncios.build(annuncio_params)
    @annuncio[:visibilita]=3
    @annuncio[:utente_id]=current_utente.id
    if @annuncio.save!
      redirect_to annuncios_path
    else
      redirect_to new_annuncio
    end
  end

  def destroy
  end

  private

    def annuncio_params
      params.require(:annuncio).permit(:descrizione,:prezzo)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        redirect_to login_url
      end
    end

end

app/controllers/facolta_controller.rb
class FacoltaController < ApplicationController
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
end

app/controllers/libros_controller.rb
class LibrosController < ApplicationController
	before_action :find_libro, only: [:show,:edit,:update,:destroy]

	def index
		@libros = Libro.all.order("created_at DESC")
	end

	def show
	end

	def new 
		@libro = Libro.new
	end

	def create
		@libro = Libro.new(libro_params)

		if @libro.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @libro.update(libro_params)
			redirect_to libro_path(@libro)
		else
			render 'edit'
		end
	end

	def destroy
		@libro.destroy
		redirect_to root_path
	end

	private 

		def libro_params
			params.require(:libro).permit(:ISBN,:titolo,:autore)
		end
		def find_libro
			#Il campo id qua sotto in realtà è il campo ISBN!
			@libro = Libro.find(params[:id])
		end

end

app/controllers/regiones_controller.rb
class RegionesController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    utente = Utente.find_by(username: params[:session][:username].downcase)
    if utente && utente.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in utente
      redirect_to utente
    else
      # Create an error message.
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/utentes_controller.rb
class UtentesController < ApplicationController
	before_action :find_utente, only: [:show,:edit,:update,:destroy]
	def index
		@utentes = Utente.all.order("created_at DESC")
	end


	def new 
		@utente = Utente.new
	end

	def create
		@utente = Utente.new(utente_params)
		if @utente.save
      		redirect_to utente_path(@utente)
   	 	else
      		render 'new'
    	end
	end

	def show
		@utente = Utente.find(params[:id])
    	@annuncios = @utente.annuncios.paginate(page: params[:page])
	end

	def destroy
		@utente.destroy
		redirect_to utentes_path
	end
	
	private 

		def utente_params
			params.require(:utente).permit(:username,:nome,:cognome,:password,:email,:telefono,:password_confirmation)
		end
		def find_utente
			#Il campo id qua sotto in realtà è il campo username!
			@utente = Utente.find(params[:id])
		end
end

app/helpers/annuncios_helper.rb
module AnnunciosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facolta_helper.rb
module FacoltaHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/libros_helper.rb
module LibrosHelper
end

app/helpers/regiones_helper.rb
module RegionesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(utente)
    session[:user_id] = utente.id
    
  end

  # Returns the current logged-in user (if any).
  def current_utente
    @current_utente ||= Utente.find_by(username: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_utente.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_utente = nil
  end

end

app/helpers/utentes_helper.rb
module UtentesHelper
end

app/views/annuncios/_annuncios.html.erb
<li id="<%= annuncio.id %>">
  <%= link_to gravatar_for(annuncio.utente, size: 50), annuncio.utente %>
  <span class="user"><%= link_to annuncio.utente.nome, annuncio.utente %></span>
  <span class="content"><%= annuncio.descrizione %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(annuncio.created_at) %> ago.
    <% if current_utente?(annuncio.utente) %>
      <%= link_to "delete", annuncio, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

app/views/annuncios/_form.html.erb
<div class="panel panel-primary col-md-4 col-md-offset-4  panel-heading">
<div class=" panel-heading">
<h3 align="center">Nuovo annuncio</h3>
</div>
<br>
<div class=" panel-body" >
<div class="col-md-8 col-md-offset-2">
<%= simple_form_for @annuncio do |f| %>
	<%= f.input :descrizione, placeholder: "descrizione...",label: false %>
	<%= f.input :prezzo, placeholder: "prezzo...",label: false %>
	<div align="center" padding="10p"><%= f.submit "Pubblica annuncio", class: "btn btn-primary" ,label: false %></div><br>
<% end %>
</div>
</div>
</div>

app/views/annuncios/index.html.erb
<h1>Lista annunci</h1>

<% @annuncios.each do |annuncio| %>
		<h2><%= annuncio.descrizione%></h2>
<% end %>

app/views/annuncios/new.html.erb
<nav class="navbar navbar-default">
  	<div class="container-fluid">
  		<div class="container-fluid navbar-left">
  			<div class="navbar-header" vlign="left">
  				<%= link_to "Bibliostud", root_path, class: "navbar-brand" %>
  			
  			</div>
  		</div>
  		<div class="container-fluid navbar-right">
        		<span class="active"><a href="#">Link<span class="sr-only">(current)</span></a></span>

  		</div>

  	</div>
  	
</nav>

<%= render 'form' %>
<%= render 'libros/form' %>

app/views/libros/_form.html.erb
<%= simple_form_for @libro do |f| %>
	<%= f.input :titolo, label: "Titolo" %>
	<%= f.input :autore, label: "Autore" %>
	<%= f.input :ISBN, label: "ISBN" %>
	<%= f.button :submit %>
<% end %>

app/views/libros/edit.html.erb
<h1>Modifica Libro</h1>
<%= render 'form' %>

app/views/libros/index.html.erb
<h1>Index libro</h1>

<% @libros.each do |libro| %>
		<h2><%= link_to libro.titolo+' ('+libro.autore+') '+libro.ISBN , libro_path(libro) %></h2>
<% end %>

<%= link_to "Aggiungi Libro", new_libro_path %>

app/views/libros/new.html.erb
<h1>new book</h1>
<%= render 'form' %>

app/views/libros/show.html.erb
<h2><%= @libro.titolo %></h2>
<h2><%= @libro.autore %></h2>
<h2><%= @libro.ISBN %></h2>
<%= link_to "Edit", edit_libro_path(@libro) %>
<%-# ATTENZIONE: Nella linea qui sotto non mettere link_to al posto di button_to altrimenti non funziona! -%>
<%= button_to "Delete", libro_path(@libro), method: :delete, data: { confirm: "Eliminare il libro?" } %>

app/views/utentes/_form.html.erb
<div class="panel panel-primary col-md-4 col-md-offset-4  panel-heading">
<div class=" panel-heading">
<h3 align="center">Registrazione</h3>
</div>
<br>
<div class=" panel-body" >
<div class="col-md-8 col-md-offset-2">
<%= simple_form_for @utente do |f| %>
	<%= f.input :username, placeholder: "username...",label: false %>
	<%= f.input :nome, placeholder: "nome...",label: false %>
	<%= f.input :cognome, placeholder: "cognome..." ,label: false %>
	<%= f.input :email, placeholder: "email..." ,label: false %>
	<%= f.input :telefono, placeholder: "telefono...",label: false %>
	<%= f.input :password, placeholder: "password..." ,label: false %>
	<%= f.input :password_confirmation , placeholder: "conferma password...",label: false%>
	<div align="center" padding="10p"><%= f.submit "Crea account", class: "btn btn-primary" ,label: false %></div><br>
<% end %>
</div>
</div>
</div>

app/views/utentes/index.html.erb
<h1>Lista utenti</h1>

<% @utentes.each do |utente| %>
		<h2><%= utente.username%></h2>
<% end %>

app/views/utentes/new.html.erb
<nav class="navbar navbar-default">
  	<div class="container-fluid">
  		<div class="container-fluid navbar-left">
  			<div class="navbar-header" vlign="left">
  				<%= link_to "Bibliostud", root_path, class: "navbar-brand" %>
  			
  			</div>
  		</div>
  		<div class="container-fluid navbar-right">
  			<form class="navbar-form">
        		<div class="form-group">
          			<input type="text" class="form-control" placeholder="nome utente...">
        		</div>
        		<div class="form-group">
          			<input type="password" class="form-control" placeholder="password...">
        		</div>
        		<button type="submit" class="btn btn-default">Accedi</button>
        		<span class="active"><a href="/utentes/new">Registrati<span class="sr-only">(current)</span></a></span>
      		</form>

  		</div>

  	</div>
  	
</nav>

<%= render 'form' %>

app/views/utentes/show.html.erb
<h2>Ciao, <%= @utente.nome %></h2>
<div align="left">
<a href="/new_annuncio">Inserisci annuncio<span class="sr-only">(current)</span></a>
</div>
<div class="col-md-8">
<h3>Annunci (<%= @utente.annuncios.count %>)</h3>
    <% if @utente.annuncios.any? %>
      <% @utente.annuncios.each do |annuncio| %>
		<h2><%= annuncio.descrizione%></h2>
<% end %>

    <% end %>
 </div>


<br><br><br><br><br>
<br><br><br><br><br>
<br><br><br><br><br>
<br><br><br><br><br>
 <%= button_to "Delete", utente_path(@utente), method: :delete, data: { confirm: "Eliminare utente?" } %>